// <auto-generated />
using System;
using Airlines.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Airlines.API.Migrations
{
    [DbContext(typeof(AirlinesDbContext))]
    [Migration("20260312094020_AddDomainSchema")]
    partial class AddDomainSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Airlines.API.Models.Airplane", b =>
                {
                    b.Property<int>("AirplaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AirplaneId"));

                    b.Property<int>("NumSeats")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalFuel")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AirplaneId");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("Airlines.API.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AirportId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AirportId");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Airlines.API.Models.Buy", b =>
                {
                    b.Property<int>("BuyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BuyId"));

                    b.Property<DateOnly>("BuyDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("BuyTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("BuyId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmpId");

                    b.ToTable("Buys");
                });

            modelBuilder.Entity("Airlines.API.Models.Crew", b =>
                {
                    b.Property<int>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CrewId"));

                    b.Property<int>("CommanderId")
                        .HasColumnType("integer");

                    b.Property<int>("CopiloteId")
                        .HasColumnType("integer");

                    b.Property<int>("FachiefId")
                        .HasColumnType("integer");

                    b.Property<int>("FliAttendant1Id")
                        .HasColumnType("integer");

                    b.Property<int>("FliAttendant2Id")
                        .HasColumnType("integer");

                    b.Property<int>("FliAttendant3Id")
                        .HasColumnType("integer");

                    b.HasKey("CrewId");

                    b.HasIndex("CommanderId");

                    b.HasIndex("CopiloteId");

                    b.HasIndex("FachiefId");

                    b.HasIndex("FliAttendant1Id");

                    b.HasIndex("FliAttendant2Id");

                    b.HasIndex("FliAttendant3Id");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("Airlines.API.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeptId"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeptId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Airlines.API.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpId"));

                    b.Property<string>("Addre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("AdmiDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeptId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Airlines.API.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlightId"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("integer");

                    b.Property<int>("AirportArrId")
                        .HasColumnType("integer");

                    b.Property<int>("AirportDepId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ArrTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("DepTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("FlightDate")
                        .HasColumnType("date");

                    b.Property<string>("FlightNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("TotBagga")
                        .HasColumnType("integer");

                    b.Property<int>("TotPass")
                        .HasColumnType("integer");

                    b.HasKey("FlightId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("AirportArrId");

                    b.HasIndex("AirportDepId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Airlines.API.Models.Passenger", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Airlines.API.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeOnly>("BeginTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("CrewId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.HasKey("ShiftId");

                    b.HasIndex("CrewId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Airlines.API.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<int>("BuyId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TicketId");

                    b.HasIndex("BuyId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FlightId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Airlines.API.Models.Buy", b =>
                {
                    b.HasOne("Airlines.API.Models.Passenger", "Client")
                        .WithMany("Buys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Airlines.API.Models.Crew", b =>
                {
                    b.HasOne("Airlines.API.Models.Employee", "Commander")
                        .WithMany("CrewsAsCommander")
                        .HasForeignKey("CommanderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Employee", "Copilote")
                        .WithMany("CrewsAsCopilote")
                        .HasForeignKey("CopiloteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Employee", "Fachief")
                        .WithMany("CrewsAsFachief")
                        .HasForeignKey("FachiefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Employee", "FliAttendant1")
                        .WithMany("CrewsAsFliAttendant1")
                        .HasForeignKey("FliAttendant1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Employee", "FliAttendant2")
                        .WithMany("CrewsAsFliAttendant2")
                        .HasForeignKey("FliAttendant2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Employee", "FliAttendant3")
                        .WithMany("CrewsAsFliAttendant3")
                        .HasForeignKey("FliAttendant3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commander");

                    b.Navigation("Copilote");

                    b.Navigation("Fachief");

                    b.Navigation("FliAttendant1");

                    b.Navigation("FliAttendant2");

                    b.Navigation("FliAttendant3");
                });

            modelBuilder.Entity("Airlines.API.Models.Department", b =>
                {
                    b.HasOne("Airlines.API.Models.Employee", "Manager")
                        .WithMany("ManagedDepartments")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Airlines.API.Models.Employee", b =>
                {
                    b.HasOne("Airlines.API.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Airlines.API.Models.Flight", b =>
                {
                    b.HasOne("Airlines.API.Models.Airplane", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Airport", "AirportArr")
                        .WithMany("ArrivingFlights")
                        .HasForeignKey("AirportArrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Airport", "AirportDep")
                        .WithMany("DepartingFlights")
                        .HasForeignKey("AirportDepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Shift", "Shift")
                        .WithMany("Flights")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");

                    b.Navigation("AirportArr");

                    b.Navigation("AirportDep");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Airlines.API.Models.Shift", b =>
                {
                    b.HasOne("Airlines.API.Models.Crew", "Crew")
                        .WithMany("Shifts")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("Airlines.API.Models.Ticket", b =>
                {
                    b.HasOne("Airlines.API.Models.Buy", "Buy")
                        .WithMany("Tickets")
                        .HasForeignKey("BuyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airlines.API.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buy");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Airlines.API.Models.Airplane", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Airlines.API.Models.Airport", b =>
                {
                    b.Navigation("ArrivingFlights");

                    b.Navigation("DepartingFlights");
                });

            modelBuilder.Entity("Airlines.API.Models.Buy", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airlines.API.Models.Crew", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Airlines.API.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Airlines.API.Models.Employee", b =>
                {
                    b.Navigation("CrewsAsCommander");

                    b.Navigation("CrewsAsCopilote");

                    b.Navigation("CrewsAsFachief");

                    b.Navigation("CrewsAsFliAttendant1");

                    b.Navigation("CrewsAsFliAttendant2");

                    b.Navigation("CrewsAsFliAttendant3");

                    b.Navigation("ManagedDepartments");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Airlines.API.Models.Flight", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airlines.API.Models.Passenger", b =>
                {
                    b.Navigation("Buys");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Airlines.API.Models.Shift", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
